
SET names 'utf8mb4';
SET character_set_database='utf8mb4';
SET collation_database ='utf8mb4_unicode_ci';
SET CHARACTER SET utf8mb4, CHARACTER_SET_CONNECTION =utf8mb4;

CREATE DATABASE IF NOT EXISTS `api`;
DROP TABLE IF EXISTS `contact`;
CREATE TABLE `contact`(
  `id` INT(11)  NOT NULL AUTO_INCREMENT PRIMARY KEY  ,
  `firstname` VARCHAR(255)NOT NULL  ,
  `lastname` VARCHAR(255)NOT NULL ,
  `email` VARCHAR(255) NOT NULL,
  `company` VARCHAR (255) NOT NULL,
  `phone` VARCHAR(24)NOT NULL ,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP 
)ENGINE=InnoDB DEFAULT CHARACTER SET =utf8mb4 ;

DROP TABLE IF EXISTS `user`;
CREATE TABLE  `user`(
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(30) NOT NULL ,
  `password` VARCHAR(255) NOT NULL  
)ENGINE=InnoDB DEFAULT CHARACTER SET =utf8mb4;
